version: "3.3"

services:
  reverse-proxy:
    image: nginx:1.17.10
    container_name: reverse-proxy
    restart: always
    depends_on: 
      - client
    volumes: 
      - ./reverse-proxy/:/etc/nginx/
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    ports: 
      - 80:80
    networks: 
      - frontend
    restart: on-failure

  certbot:
    image: certbot/certbot
    restart: unless-stopped
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    
  client:
    image: "client"
    build: 
      context: ./client/
    ports:
      - 3000
    stdin_open: true
    tty: true
    networks: 
      - frontend
    restart: always
    environment: 
      - CHOKIDAR_USEPOLLING=true
    volumes: 
      - ./client:/app

      
networks:
  frontend:
    driver: bridge
